CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE app_user_favorite_heroes
(
    app_user_id        BIGINT NOT NULL,
    favorite_heroes_id BIGINT NOT NULL,
    CONSTRAINT pk_app_user_favoriteheroes PRIMARY KEY (app_user_id, favorite_heroes_id)
);

CREATE TABLE hero_roles
(
    hero_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE heroes
(
    id             BIGINT NOT NULL,
    name           VARCHAR(255),
    localized_name VARCHAR(255),
    primary_attr   VARCHAR(255),
    attack_type    VARCHAR(255),
    CONSTRAINT pk_heroes PRIMARY KEY (id)
);

ALTER TABLE app_user_favorite_heroes
    ADD CONSTRAINT fk_appusefavher_on_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE app_user_favorite_heroes
    ADD CONSTRAINT fk_appusefavher_on_hero FOREIGN KEY (favorite_heroes_id) REFERENCES heroes (id);

ALTER TABLE hero_roles
    ADD CONSTRAINT fk_hero_roles_on_hero FOREIGN KEY (hero_id) REFERENCES heroes (id);
CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE app_user_favorite_heroes
(
    app_user_id        BIGINT NOT NULL,
    favorite_heroes_id BIGINT NOT NULL,
    CONSTRAINT pk_app_user_favoriteheroes PRIMARY KEY (app_user_id, favorite_heroes_id)
);

CREATE TABLE hero_roles
(
    hero_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE heroes
(
    id             BIGINT NOT NULL,
    name           VARCHAR(255),
    localized_name VARCHAR(255),
    primary_attr   VARCHAR(255),
    attack_type    VARCHAR(255),
    CONSTRAINT pk_heroes PRIMARY KEY (id)
);

ALTER TABLE app_user_favorite_heroes
    ADD CONSTRAINT fk_appusefavher_on_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE app_user_favorite_heroes
    ADD CONSTRAINT fk_appusefavher_on_hero FOREIGN KEY (favorite_heroes_id) REFERENCES heroes (id);

ALTER TABLE hero_roles
    ADD CONSTRAINT fk_hero_roles_on_hero FOREIGN KEY (hero_id) REFERENCES heroes (id);